Fix sig n cipher functions
distubejs/ytdl-core pull request #139
Opened 2024-12-12 21:20 UTC by ToddyTheNoobDud

this fixes everything from the sig related stuff (example: Could not parse n transform function, 403, and others)

2024-12-12 22:07 UTC, ToddyTheNoobDud commented
i forgot to remove my own performance rewrite (💀 ), only needs the [a800d42](https://github.com/distubejs/ytdl-core/pull/139/commits/a800d422a52c53c512443e31d8f75b6b2333b899) commit to work again...

2024-12-15 08:52 UTC, skick1234 requested changes
I will close this and fix the regex myself.
You can split this into some pull requests for easier merging.

2024-12-15 08:52 UTC, skick1234 commented on lib/agent.js
> +      return "None";
I don't think this is needed

2024-12-15 08:52 UTC, skick1234 commented on lib/agent.js
> +};
The inline won't allocate a new object basically because it doesn't run

2024-12-15 08:52 UTC, skick1234 commented on lib/agent.js
> +  const options = { ...opts };
Object.assign is faster than spread

2024-12-15 08:52 UTC, skick1234 commented on lib/agent.js
> +};
Not necessary. But I will apply this if someone create a pull request contains this.

2024-12-15 08:52 UTC, skick1234 commented on lib/sig.js
> +const timestampPattern = /(?:signatureTimestamp|sts):(\d+)/;
timestampPattern is not used

2024-12-15 08:52 UTC, skick1234 commented on lib/agent.js
> +
Object.assign is faster than spread

2024-12-15 08:52 UTC, skick1234 commented on lib/sig.js
> +const AFTER_ACCESS = "(?:\\\"\\]|)";
Unnecessary changes

2024-12-15 08:52 UTC, skick1234 commented on lib/sig.js
> +      `https://github.com/ToddyTheNoobDud/ytdl-core-toddys/issues`,
Revert this

2024-12-15 08:52 UTC, closed without merging